import React, { useState } from 'react';
import { Note } from '../types';
import { 
  Brain, 
  BookOpen, 
  HelpCircle, 
  Award, 
  ChevronRight, 
  ChevronLeft, 
  RefreshCw, 
  CheckCircle, 
  XCircle, 
  FileText, 
  Save, 
  Eye, 
  ArrowLeft 
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface QuizWorkspaceProps {
  notes: Note[];
  onUpdateNote: (updatedNote: Note) => Promise<void>;
  onClose: () => void;
  isDark: boolean;
}

interface QuizQuestion {
  question: string;
  options: string[];
  correctOptionIndex: number;
  explanation: string;
}

export default function QuizWorkspace({ notes, onUpdateNote, onClose, isDark }: QuizWorkspaceProps) {
  // Configuration states
  const [selectedNoteId, setSelectedNoteId] = useState<string>(notes[0]?.id || '');
  const [numQuestions, setNumQuestions] = useState<number>(5);
  const [difficulty, setDifficulty] = useState<'easy' | 'medium' | 'hard'>('medium');
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  // Active Quiz states
  const [quizQuestions, setQuizQuestions] = useState<QuizQuestion[]>([]);
  const [quizStarted, setQuizStarted] = useState<boolean>(false);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState<number>(0);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, number>>({});
  const [quizSubmitted, setQuizSubmitted] = useState<boolean>(false);
  const [reviewSavedSuccess, setReviewSavedSuccess] = useState<boolean>(false);

  const activeNotes = notes.filter(n => !n.isDeleted);
  const selectedNote = activeNotes.find(n => n.id === selectedNoteId);

  // Formats note blocks content into comprehensive context string
  const getNoteTextContent = (note: Note): string => {
    return note.blocks
      .map(block => {
        if (block.type === 'heading-1' || block.type === 'heading-2' || block.type === 'heading-3') {
          return `### ${block.content}`;
        }
        if (block.type === 'table' && block.tableData) {
          return block.tableData.map(row => row.join(' | ')).join('\n');
        }
        if (block.type === 'quote') {
          return `> ${block.content}`;
        }
        return block.content.replace(/<[^>]*>/g, ''); // strip HTML tags
      })
      .join('\n\n');
  };

  // Start the AI generation requests
  const handleGenerateQuiz = async () => {
    if (!selectedNote) {
      setError("Please select a study note before continuing.");
      return;
    }

    const content = getNoteTextContent(selectedNote);
    if (!content.trim()) {
      setError("The selected note does not have enough content blocks structure to generate assessment questions. Please write or insert texts first.");
      return;
    }

    setIsGenerating(true);
    setError(null);
    setReviewSavedSuccess(false);

    try {
      const response = await fetch('/api/quiz/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          noteTitle: selectedNote.title || 'Untitled Note',
          noteContent: content,
          numQuestions,
          difficulty,
        }),
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || 'Server error occurred during generation.');
      }

      if (data.quiz && data.quiz.length > 0) {
        setQuizQuestions(data.quiz);
        setQuizStarted(true);
        setCurrentQuestionIndex(0);
        setSelectedAnswers({});
        setQuizSubmitted(false);
      } else {
        throw new Error("No questions were generated by AI. Try increasing your note size or choosing a lighter topic.");
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Connecting to Gemini failed. Check your network or API Key status.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Handles checking user attempt results and appending wrong answers to "Review Notes"
  const handleQuizSubmit = async () => {
    setQuizSubmitted(true);

    // Filter incorrect answers
    const incorrects = quizQuestions.filter((q, index) => {
      const uAnswer = selectedAnswers[index];
      return uAnswer === undefined || uAnswer !== q.correctOptionIndex;
    });

    if (incorrects.length === 0) {
      setReviewSavedSuccess(true);
      return; // A perfect score!
    }

    try {
      // Find or build the "Review Notes" document
      const existingReviewNote = notes.find(n => n.title.trim().toLowerCase() === 'review notes' && !n.isDeleted);
      
      const newBlocks = incorrects.flatMap(q => {
        const qIndex = quizQuestions.indexOf(q);
        const userAnswerText = selectedAnswers[qIndex] !== undefined && q.options[selectedAnswers[qIndex]]
          ? q.options[selectedAnswers[qIndex]]
          : 'Unanswered / Dropped';
        const correctAnswerText = q.options[q.correctOptionIndex];
        const randomID = Math.random().toString(36).substr(2, 9);

        return [
          {
            id: `rev-h-${randomID}`,
            type: 'heading-4' as const,
            content: `Question: ${q.question}`
          },
          {
            id: `rev-ans-${randomID}`,
            type: 'paragraph' as const,
            content: `<span class="text-rose-500 font-bold">Your answer:</span> ${userAnswerText} • <span class="text-emerald-500 font-bold">Correct:</span> ${correctAnswerText}`
          },
          {
            id: `rev-call-${randomID}`,
            type: 'highlight-box' as const,
            content: `<b>Concept Explanation:</b> ${q.explanation}`,
            highlightType: 'important' as const
          },
          {
            id: `rev-div-${randomID}`,
            type: 'divider' as const,
            content: ''
          }
        ];
      });

      if (existingReviewNote) {
        const updatedNote = {
          ...existingReviewNote,
          blocks: [...existingReviewNote.blocks, ...newBlocks],
          updatedAt: Date.now()
        };
        await onUpdateNote(updatedNote);
      } else {
        const pathRandomId = Math.random().toString(36).substr(2, 9);
        const newReviewNote: Note = {
          id: `n-review-${pathRandomId}`,
          folderId: null,
          title: 'Review Notes',
          coverEmoji: '🎯',
          coverImage: 'linear-gradient(135deg, #ef4444 0%, #b91c1c 100%)',
          createdAt: Date.now(),
          updatedAt: Date.now(),
          pinned: true,
          isDeleted: false,
          tags: ['review', 'quiz-errors'],
          blocks: [
            { id: `rev-title-${pathRandomId}`, type: 'heading-1' as const, content: 'Review Notes' },
            { id: `rev-desc-${pathRandomId}`, type: 'paragraph' as const, content: 'This review folder aggregates your wrong answers from dynamic quizzes, complete with deep analytical concepts explanation from Google Gemini.' },
            { id: `doc-div-${pathRandomId}`, type: 'divider' as const, content: '' },
            ...newBlocks
          ]
        };
        await onUpdateNote(newReviewNote);
      }
      setReviewSavedSuccess(true);
    } catch (saveError) {
      console.error("Failed to sync errors into 'Review Notes':", saveError);
    }
  };

  const scoreCount = quizQuestions.reduce((acc, q, index) => {
    return selectedAnswers[index] === q.correctOptionIndex ? acc + 1 : acc;
  }, 0);

  const totalPossible = quizQuestions.length;
  const percentage = totalPossible > 0 ? Math.round((scoreCount / totalPossible) * 100) : 0;

  return (
    <div id="ai-quiz-workspace-root" className={`flex-1 h-full flex flex-col overflow-y-auto scrollbar-thin p-4 sm:p-8 select-text ${
      isDark ? 'bg-zinc-950 text-zinc-100' : 'bg-zinc-50/50 text-zinc-800'
    }`}>
      
      {/* Top Banner Toolbar */}
      <div className="max-w-3xl mx-auto w-full flex items-center justify-between mb-6 pb-4 border-b border-zinc-200/40 dark:border-zinc-900 select-none">
        <button
          onClick={onClose}
          className={`flex items-center gap-1 text-xs font-bold transition rounded-lg py-1.5 px-3 border cursor-pointer ${
            isDark 
              ? 'bg-zinc-900 border-zinc-800 hover:bg-zinc-800 text-zinc-400 hover:text-white' 
              : 'bg-white border-zinc-200 text-zinc-500 hover:text-zinc-800 hover:bg-zinc-100'
          }`}
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          <span>Back to Notes Desk</span>
        </button>

        <div className="flex items-center gap-1.5">
          <Brain className="h-5 w-5 text-indigo-500 animate-pulse animate-duration-1000" />
          <span className="font-sans font-extrabold text-sm uppercase tracking-wide opacity-80">AI Quiz Arena</span>
        </div>
      </div>

      <div className="max-w-3xl mx-auto w-full flex-1 flex flex-col">
        {!quizStarted ? (
          /* CONFIGURATION VIEW SPACE */
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            className={`border rounded-2xl p-6 sm:p-8 space-y-6 ${
              isDark ? 'bg-zinc-900/60 border-zinc-900' : 'bg-white border-zinc-200/80 shadow-[0_4px_24px_rgba(0,0,0,0.02)]'
            }`}
          >
            <div className="space-y-1.5">
              <h1 className="text-xl sm:text-2xl font-extrabold font-sans tracking-tight">Generate Study Assessment</h1>
              <p className="text-xs text-zinc-400">Google Gemini analyzes your personal notes to prepare professional multiple-choice testing questions.</p>
            </div>

            {error && (
              <div className="p-3.5 rounded-xl border border-red-500/10 bg-red-500/5 text-xs text-red-500 flex items-start gap-2 select-text">
                <XCircle className="h-4 w-4 shrink-0 mt-0.5" />
                <p>{error}</p>
              </div>
            )}

            {/* Dropdown Selector for Notes source */}
            <div className="space-y-2">
              <label className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block">1. Select Note Source</label>
              {activeNotes.length === 0 ? (
                <div className="p-4 border rounded-xl text-center text-xs text-zinc-500 italic bg-zinc-950/20">
                  No active notes found. Open notes and write content before starting!
                </div>
              ) : (
                <div className="relative">
                  <select
                    value={selectedNoteId}
                    onChange={e => setSelectedNoteId(e.target.value)}
                    disabled={isGenerating}
                    className={`w-full border rounded-xl px-4 py-3 text-xs font-semibold focus:outline-none appearance-none cursor-pointer ${
                      isDark 
                        ? 'bg-zinc-950 border-zinc-800 text-zinc-200' 
                        : 'bg-zinc-50 border-zinc-200 text-zinc-850'
                    }`}
                  >
                    {activeNotes.map(note => (
                      <option key={note.id} value={note.id}>
                        {note.coverEmoji || '📝'} {note.title ? note.title : 'Untitled Concept Note'}
                      </option>
                    ))}
                  </select>
                  <div className="absolute right-4 top-3.5 pointer-events-none opacity-60">
                    <BookOpen className="h-4 w-4" />
                  </div>
                </div>
              )}
            </div>

            {/* Questions difficulty and length grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              
              {/* Question Count Selector */}
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block">2. Questions Volume</label>
                <div className="relative">
                  <select
                    value={numQuestions}
                    onChange={e => setNumQuestions(Number(e.target.value))}
                    disabled={isGenerating}
                    className={`w-full border rounded-xl px-4 py-2.5 text-xs font-semibold focus:outline-none cursor-pointer ${
                      isDark 
                        ? 'bg-zinc-950 border-zinc-800 text-zinc-200' 
                        : 'bg-zinc-50 border-zinc-200 text-zinc-850'
                    }`}
                  >
                    <option value="3">3 Rapid Questions</option>
                    <option value="5">5 Comprehensive Questions</option>
                    <option value="10">10 Revision Questions</option>
                    <option value="15">15 In-depth Exam Questions</option>
                  </select>
                </div>
              </div>

              {/* Difficulty Selector */}
              <div className="space-y-2">
                <label className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider block">3. Difficulty Rating</label>
                <div className="flex gap-1.5">
                  {(['easy', 'medium', 'hard'] as const).map(d => {
                    const isSelected = difficulty === d;
                    const diffColors = {
                      easy: 'border-emerald-500/20 bg-emerald-505/10 text-emerald-500',
                      medium: 'border-amber-500/20 bg-amber-505/10 text-amber-500',
                      hard: 'border-rose-500/20 bg-rose-505/10 text-rose-500',
                    };
                    return (
                      <button
                        key={d}
                        type="button"
                        onClick={() => setDifficulty(d)}
                        disabled={isGenerating}
                        className={`flex-1 py-2 rounded-xl text-xs font-bold border transition capitalize cursor-pointer ${
                          isSelected
                            ? diffColors[d]
                            : isDark
                              ? 'bg-zinc-950 border-zinc-800 text-zinc-450 hover:text-zinc-250 hover:bg-zinc-900'
                              : 'bg-zinc-100/50 border-zinc-200 text-zinc-500 hover:text-zinc-800 hover:bg-zinc-100'
                        }`}
                      >
                        {d}
                      </button>
                    );
                  })}
                </div>
              </div>

            </div>

            {/* Launch CTA Trigger */}
            <button
              onClick={handleGenerateQuiz}
              disabled={isGenerating || activeNotes.length === 0}
              className={`w-full py-4 rounded-xl text-xs font-extrabold shadow-lg transition duration-200 flex items-center justify-center gap-2 select-none border-b-2 active:scale-[0.99] cursor-pointer ${
                isGenerating
                  ? 'bg-zinc-800 border-zinc-900 text-zinc-400'
                  : 'bg-indigo-600 hover:bg-indigo-500 border-indigo-750 text-white hover:shadow-indigo-506/20'
              }`}
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="h-4 w-4 animate-spin" />
                  <span>Google Gemini is generating revisions...</span>
                </>
              ) : (
                <>
                  <Brain className="h-4 w-4" />
                  <span>Initiate Study Assessment</span>
                </>
              )}
            </button>

            {isGenerating && (
              <div className="text-center space-y-2 animate-pulse mt-2 duration-1000 select-none">
                <p className="text-[10px] uppercase font-mono tracking-widest text-indigo-500 font-bold">Concept Analysis in Progress</p>
                <p className="text-[10px] text-zinc-500 italic font-medium leading-relaxed">
                  "Parsing your formulas, headings and tables to create deep conceptual evaluation questions..."
                </p>
              </div>
            )}
          </motion.div>
        ) : (
          /* ACTIVE EXAM / REVIEW ATTEMPT MODE */
          <div className="space-y-6">
            
            {/* Navigational Toolbar for Exam */}
            <div className={`border rounded-2xl p-4 flex items-center justify-between select-none ${
              isDark ? 'bg-zinc-900/60 border-zinc-900' : 'bg-white border-zinc-200 shadow-xs'
            }`}>
              <div className="flex items-center gap-3">
                <div className={`w-9 h-9 rounded-xl flex items-center justify-center font-bold text-xs border ${
                  isDark ? 'bg-zinc-950 border-zinc-800 text-indigo-400' : 'bg-indigo-50 border-indigo-100 text-indigo-600'
                }`}>
                  {quizSubmitted ? <Award className="h-4.5 w-4.5" /> : `${currentQuestionIndex + 1}/${totalPossible}`}
                </div>
                <div>
                  <h3 className="font-bold text-xs">
                    {quizSubmitted ? "Assessment Results Completed" : `Quiz: ${selectedNote?.title || 'Untitled note'}`}
                  </h3>
                  <span className="text-[9px] font-mono tracking-wider text-indigo-500 uppercase font-bold">
                    Difficulty: {difficulty}
                  </span>
                </div>
              </div>

              {quizSubmitted && (
                <button
                  onClick={() => setQuizStarted(false)}
                  className={`py-1.5 px-3 rounded-lg text-xs font-bold transition flex items-center gap-1.5 cursor-pointer border ${
                    isDark 
                      ? 'bg-zinc-950 border-zinc-805 hover:bg-zinc-800 text-zinc-200' 
                      : 'bg-zinc-900 text-zinc-50 hover:bg-zinc-800'
                  }`}
                >
                  <RefreshCw className="h-3 w-3" />
                  <span>Generate New Test</span>
                </button>
              )}
            </div>

            <AnimatePresence mode="wait">
              {!quizSubmitted ? (
                /* SINGLE QUESTION ATTEMPT CARD */
                <motion.div
                  key={`q-${currentQuestionIndex}`}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  transition={{ duration: 0.15 }}
                  className={`border rounded-3xl p-6 sm:p-8 space-y-6 flex flex-col justify-between ${
                    isDark ? 'bg-zinc-900/40 border-zinc-900' : 'bg-white border-zinc-200/80 shadow-md'
                  }`}
                >
                  <div className="space-y-4">
                    <span className="text-[10px] font-mono font-bold uppercase tracking-widest text-indigo-500">
                      Standard Assessment Question #{currentQuestionIndex + 1}
                    </span>
                    <h2 className="text-base sm:text-lg font-extrabold leading-relaxed font-sans text-stone-900 dark:text-stone-100">
                      {quizQuestions[currentQuestionIndex].question}
                    </h2>
                  </div>

                  {/* Options Selector List */}
                  <div className="space-y-2 py-3 select-none">
                    {quizQuestions[currentQuestionIndex].options.map((option, index) => {
                      const isSelected = selectedAnswers[currentQuestionIndex] === index;
                      const optionLabel = String.fromCharCode(65 + index); // A, B, C, D
                      
                      return (
                        <button
                          key={`opt-${index}`}
                          type="button"
                          onClick={() => {
                            setSelectedAnswers(prev => ({
                              ...prev,
                              [currentQuestionIndex]: index
                            }));
                          }}
                          className={`w-full flex items-center gap-3.5 px-4 py-3 sm:py-3.5 rounded-2xl text-xs font-semibold text-left border transition-all duration-150 active:scale-[0.99] cursor-pointer ${
                            isSelected
                              ? 'bg-indigo-500/10 border-indigo-600 text-indigo-500 dark:text-indigo-400 shadow-xs'
                              : isDark
                                ? 'bg-zinc-950 border-zinc-805 text-zinc-350 hover:border-zinc-700 hover:text-zinc-200'
                                : 'bg-zinc-50 border-zinc-200 text-zinc-650 hover:bg-zinc-100 hover:text-zinc-850'
                          }`}
                        >
                          <span className={`w-6.5 h-6.5 rounded-lg flex items-center justify-center font-bold text-[10px] border transition ${
                            isSelected
                              ? 'bg-indigo-600 text-white border-indigo-500'
                              : isDark
                                ? 'bg-zinc-900 border-zinc-800 text-zinc-500'
                                : 'bg-white border-zinc-200 text-zinc-400'
                          }`}>
                            {optionLabel}
                          </span>
                          <span className="flex-1 leading-snug">{option}</span>
                        </button>
                      );
                    })}
                  </div>

                  {/* Question Controls Prev/Next Toolbar */}
                  <div className="flex items-center justify-between border-t border-zinc-200/30 dark:border-zinc-850 pt-5 mt-4 select-none">
                    <button
                      type="button"
                      disabled={currentQuestionIndex === 0}
                      onClick={() => setCurrentQuestionIndex(prev => prev - 1)}
                      className={`flex items-center gap-1 py-2 px-3.5 rounded-xl text-xs font-bold transition cursor-pointer disabled:opacity-30 disabled:pointer-events-none ${
                        isDark ? 'bg-zinc-950 text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900' : 'bg-zinc-100 text-zinc-600 hover:bg-zinc-200'
                      }`}
                    >
                      <ChevronLeft className="h-4 w-4" />
                      <span>Prev</span>
                    </button>

                    {currentQuestionIndex < totalPossible - 1 ? (
                      <button
                        type="button"
                        onClick={() => setCurrentQuestionIndex(prev => prev + 1)}
                        className={`flex items-center gap-1 py-2 px-4.5 rounded-xl text-xs font-extrabold transition cursor-pointer ${
                          isDark ? 'bg-indigo-600 hover:bg-indigo-500 text-white' : 'bg-zinc-900 text-zinc-50 hover:bg-zinc-800'
                        }`}
                      >
                        <span>Next Question</span>
                        <ChevronRight className="h-4 w-4" />
                      </button>
                    ) : (
                      <button
                        type="button"
                        onClick={handleQuizSubmit}
                        className="py-2.5 px-6 rounded-2xl text-xs font-extrabold bg-indigo-600 hover:bg-indigo-500 text-white border-b-2 border-indigo-750 hover:shadow-lg transition select-none active:scale-95 cursor-pointer"
                      >
                        Submit Assessment
                      </button>
                    )}
                  </div>
                </motion.div>
              ) : (
                /* QUIZ ANALYSIS & RESULT CARD */
                <motion.div
                  initial={{ opacity: 0, scale: 0.98 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="space-y-6"
                >
                  {/* Circular & Metrics Summary Score card */}
                  <div className={`border rounded-3xl p-6 sm:p-8 text-center space-y-5 relative overflow-hidden ${
                    isDark ? 'bg-zinc-900 border-zinc-800' : 'bg-white border-zinc-200 shadow-lg'
                  }`}>
                    <div className="space-y-1 select-none">
                      <span className="text-[10px] uppercase font-mono tracking-widest text-indigo-500 font-bold">Assessment Summary</span>
                      <h2 className="text-xl sm:text-2xl font-black">
                        {percentage === 100 
                          ? "🏆 Perfect Score! Stellar work."
                          : percentage >= 80 
                            ? "✨ Excellent Understanding!"
                            : percentage >= 50
                              ? "📚 Good effort! Review is useful."
                              : "✍️ Practice study needed."}
                      </h2>
                    </div>

                    <div className="flex flex-col items-center select-none py-2">
                      <div className="relative w-28 h-28 flex items-center justify-center">
                        {/* Circle Backdrop */}
                        <svg className="absolute w-28 h-28 transform -rotate-90">
                          <circle cx="56" cy="56" r="48" strokeWidth="4" stroke={isDark ? '#27272a' : '#f4f4f5'} fill="transparent" />
                          <circle 
                            cx="56" 
                            cy="56" 
                            r="48" 
                            strokeWidth="5" 
                            stroke="#4f46e5" 
                            fill="transparent" 
                            strokeDasharray={301.6} 
                            strokeDashoffset={301.6 - (301.6 * percentage) / 100} 
                            strokeLinecap="round"
                            className="transition-all duration-1000"
                          />
                        </svg>
                        <div className="text-center">
                          <span className="text-3xl font-black">{scoreCount}</span>
                          <span className="text-zinc-500 font-bold text-xs"> / {totalPossible}</span>
                        </div>
                      </div>
                    </div>

                    {/* Mistakes saving feedback overlay */}
                    {reviewSavedSuccess && (
                      <div className="mx-auto max-w-md p-3 rounded-2xl border border-emerald-500/10 bg-emerald-500/5 text-xs text-emerald-500 flex items-center justify-center gap-2 font-semibold">
                        <CheckCircle className="h-4 w-4" />
                        <span>Wrong answers are compiled under "Review Notes"!</span>
                      </div>
                    )}
                  </div>

                  {/* Comprehensive List of Questions with Explanation detail */}
                  <div className="space-y-4">
                    <h3 className="text-xs font-bold uppercase tracking-wider text-zinc-500 select-none pl-1">Explanations & Revision Details</h3>
                    
                    {quizQuestions.map((q, index) => {
                      const uAnswer = selectedAnswers[index];
                      const isCorrect = uAnswer === q.correctOptionIndex;
                      const uAnswerText = uAnswer !== undefined ? q.options[uAnswer] : 'No input given';
                      const correctText = q.options[q.correctOptionIndex];

                      return (
                        <div
                          key={`q-res-${index}`}
                          className={`border rounded-2xl p-5 sm:p-6 space-y-4 transition ${
                            isDark ? 'bg-zinc-900/30 border-zinc-900' : 'bg-white border-zinc-200/65 shadow-xs'
                          }`}
                        >
                          <div className="flex items-start gap-2.5">
                            {isCorrect ? (
                              <CheckCircle className="h-4.5 w-4.5 text-emerald-500 mt-0.5 shrink-0" />
                            ) : (
                              <XCircle className="h-4.5 w-4.5 text-rose-500 mt-0.5 shrink-0" />
                            )}
                            <div>
                              <span className="text-[10px] font-mono font-semibold text-zinc-500 uppercase tracking-widest block select-none">
                                Question #{index + 1}
                              </span>
                              <h4 className="text-sm font-bold text-stone-900 dark:text-stone-100 mt-0.5 leading-relaxed">
                                {q.question}
                              </h4>
                            </div>
                          </div>

                          {/* Options visualization with colors */}
                          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 select-none">
                            {q.options.map((opt, oIdx) => {
                              const isUsersChoice = uAnswer === oIdx;
                              const isCorrectOption = q.correctOptionIndex === oIdx;

                              let optBorder = isDark ? 'border-zinc-805' : 'border-zinc-200';
                              let optBg = 'bg-transparent';
                              let optText = isDark ? 'text-zinc-400' : 'text-zinc-500';

                              if (isCorrectOption) {
                                optBorder = 'border-emerald-500/20';
                                optBg = 'bg-emerald-505/10';
                                optText = 'text-emerald-500 font-semibold';
                              } else if (isUsersChoice) {
                                optBorder = 'border-rose-500/20';
                                optBg = 'bg-rose-505/10';
                                optText = 'text-rose-500 font-semibold';
                              }

                              return (
                                <div
                                  key={`ans-res-${oIdx}`}
                                  className={`border rounded-xl px-3 py-2 text-xs flex items-center gap-2 font-medium ${optBorder} ${optBg} ${optText}`}
                                >
                                  <span className={`w-5 h-5 rounded flex items-center justify-center font-bold text-[9px] border ${
                                    isCorrectOption
                                      ? 'bg-emerald-500 text-white border-emerald-400'
                                      : isUsersChoice
                                        ? 'bg-rose-500 text-white border-rose-450'
                                        : isDark
                                          ? 'bg-zinc-950 border-zinc-800 text-zinc-500'
                                          : 'bg-white border-zinc-200 text-zinc-405'
                                  }`}>
                                    {String.fromCharCode(65 + oIdx)}
                                  </span>
                                  <span className="leading-snug truncate">{opt}</span>
                                </div>
                              );
                            })}
                          </div>

                          {/* Explanation Card block */}
                          <div className={`p-4 rounded-xl border flex items-start gap-2.5 text-xs focus:ring-1 leading-normal ${
                            isCorrect 
                              ? (isDark ? 'bg-zinc-950/40 border-zinc-850/50 text-zinc-300' : 'bg-zinc-50/50 border-zinc-150 text-zinc-600')
                              : (isDark ? 'bg-rose-505/5 border-rose-500/10 text-rose-200' : 'bg-red-500/5 border-red-200/50 text-rose-700')
                          }`}>
                            <HelpCircle className="h-4.5 w-4.5 text-indigo-400 shrink-0 mt-0.5" />
                            <div>
                              <strong className="block font-bold mb-1 font-mono uppercase tracking-widest text-[9px] text-zinc-500">
                                Concept Explanation:
                              </strong>
                              <span>{q.explanation}</span>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        )}
      </div>
    </div>
  );
}
